@baseUrl = http://localhost:3002

@jwtToken = {{authLogin.response.body.accesToken }}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "joao@gmail.com",
    "password": "654321"
}

### Read one user
# @name readOneUser
GET {{baseUrl}}/user/123
Authorization: Bearer {{jwtToken}}

### Create user
# @name CreateUser
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "joão gomes",
    "email": "joaoGomes@email.com",
    "password": "123456"
}

### Update user
# @name UpdateUser
PATCH {{baseUrl}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "name": "Joao1",
    "email": "joao@gmail.com"
}

### Update user password
# @name UpdateUserPassword
PATCH {{baseUrl}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
    "currentPassword": "123456",
    "newPassword": "123456"
}